///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace IntegrityService
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the IntegrityServiceRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("5a9fcdd2-ddc4-491c-8473-f77d9e53725d")]
    public partial class IntegrityServiceRepository : RepoGenBaseFolder
    {
        static IntegrityServiceRepository instance = new IntegrityServiceRepository();
        IntegrityServiceRepositoryFolders.ExplorerAppFolder _explorer;
        IntegrityServiceRepositoryFolders.UntitledGoogleChromeAppFolder _untitledgooglechrome;
        IntegrityServiceRepositoryFolders.WelcomeProMonitorInternetExplorerAppFolder _welcomepromonitorinternetexplorer;
        IntegrityServiceRepositoryFolders.WelcomeProMonitorAppFolder _welcomepromonitor;

        /// <summary>
        /// Gets the singleton class instance representing the IntegrityServiceRepository element repository.
        /// </summary>
        [RepositoryFolder("5a9fcdd2-ddc4-491c-8473-f77d9e53725d")]
        public static IntegrityServiceRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public IntegrityServiceRepository() 
            : base("IntegrityServiceRepository", "/", null, 0, false, "5a9fcdd2-ddc4-491c-8473-f77d9e53725d", ".\\RepositoryImages\\IntegrityServiceRepository5a9fcdd2.rximgres")
        {
            _explorer = new IntegrityServiceRepositoryFolders.ExplorerAppFolder(this);
            _untitledgooglechrome = new IntegrityServiceRepositoryFolders.UntitledGoogleChromeAppFolder(this);
            _welcomepromonitorinternetexplorer = new IntegrityServiceRepositoryFolders.WelcomeProMonitorInternetExplorerAppFolder(this);
            _welcomepromonitor = new IntegrityServiceRepositoryFolders.WelcomeProMonitorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5a9fcdd2-ddc4-491c-8473-f77d9e53725d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("d67516f9-2d64-43b4-aeb9-32eb40eee68b")]
        public virtual IntegrityServiceRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The UntitledGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("739cb309-8e4a-43d4-853f-fabee63b36d2")]
        public virtual IntegrityServiceRepositoryFolders.UntitledGoogleChromeAppFolder UntitledGoogleChrome
        {
            get { return _untitledgooglechrome; }
        }

        /// <summary>
        /// The WelcomeProMonitorInternetExplorer folder.
        /// </summary>
        [RepositoryFolder("25473e6a-937c-40df-8b98-fe10027da50b")]
        public virtual IntegrityServiceRepositoryFolders.WelcomeProMonitorInternetExplorerAppFolder WelcomeProMonitorInternetExplorer
        {
            get { return _welcomepromonitorinternetexplorer; }
        }

        /// <summary>
        /// The WelcomeProMonitor folder.
        /// </summary>
        [RepositoryFolder("a97540b1-e8aa-4085-b035-3aac8f33827f")]
        public virtual IntegrityServiceRepositoryFolders.WelcomeProMonitorAppFolder WelcomeProMonitor
        {
            get { return _welcomepromonitor; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class IntegrityServiceRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("d67516f9-2d64-43b4-aeb9-32eb40eee68b")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/form[@processname='explorer' and @class='TaskListThumbnailWnd']", parentFolder, 30000, null, true, "d67516f9-2d64-43b4-aeb9-32eb40eee68b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d67516f9-2d64-43b4-aeb9-32eb40eee68b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d67516f9-2d64-43b4-aeb9-32eb40eee68b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The UntitledGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("739cb309-8e4a-43d4-853f-fabee63b36d2")]
        public partial class UntitledGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _intermediated3dwindowInfo;

            /// <summary>
            /// Creates a new UntitledGoogleChrome  folder.
            /// </summary>
            public UntitledGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UntitledGoogleChrome", "/form[@title='Untitled - Google Chrome']", parentFolder, 30000, null, true, "739cb309-8e4a-43d4-853f-fabee63b36d2", "")
            {
                _intermediated3dwindowInfo = new RepoItemInfo(this, "IntermediateD3DWindow", "element[@class='Intermediate D3D Window']", 30000, null, "56a70cb7-f3c4-4e87-9ae4-749c7d4461b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("739cb309-8e4a-43d4-853f-fabee63b36d2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("739cb309-8e4a-43d4-853f-fabee63b36d2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IntermediateD3DWindow item.
            /// </summary>
            [RepositoryItem("56a70cb7-f3c4-4e87-9ae4-749c7d4461b6")]
            public virtual Ranorex.Unknown IntermediateD3DWindow
            {
                get
                {
                    return _intermediated3dwindowInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IntermediateD3DWindow item info.
            /// </summary>
            [RepositoryItemInfo("56a70cb7-f3c4-4e87-9ae4-749c7d4461b6")]
            public virtual RepoItemInfo IntermediateD3DWindowInfo
            {
                get
                {
                    return _intermediated3dwindowInfo;
                }
            }
        }

        /// <summary>
        /// The WelcomeProMonitorInternetExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("25473e6a-937c-40df-8b98-fe10027da50b")]
        public partial class WelcomeProMonitorInternetExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _container40966Info;
            RepoItemInfo _controlbandclassInfo;
            RepoItemInfo _closetabctrlpluswInfo;

            /// <summary>
            /// Creates a new WelcomeProMonitorInternetExplorer  folder.
            /// </summary>
            public WelcomeProMonitorInternetExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeProMonitorInternetExplorer", "/form[@title~'^Welcome\\ -\\ ProMonitor\\ -\\ In']", parentFolder, 30000, null, true, "25473e6a-937c-40df-8b98-fe10027da50b", "")
            {
                _container40966Info = new RepoItemInfo(this, "Container40966", "?/?/container[@controlid='40966']", 30000, null, "07e08ad3-675e-45c4-8f2e-7f451b98f81f");
                _controlbandclassInfo = new RepoItemInfo(this, "ControlBandClass", "element[@class='WorkerW']/?/?/element[@class='ControlBandClass']", 30000, null, "9ccca334-a1bc-411d-965a-e0378d6c5459");
                _closetabctrlpluswInfo = new RepoItemInfo(this, "CloseTabCtrlPlusW", ".//container[@class='TabBandClass']/?/?/tabpagelist[@accessiblename='Tab Row']/tabpage[@accessiblename='Welcome - ProMonitor']/button[@accessiblename='Close Tab (Ctrl+W)']", 30000, null, "340b592d-8784-413c-80ea-0854725ee605");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("25473e6a-937c-40df-8b98-fe10027da50b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("25473e6a-937c-40df-8b98-fe10027da50b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Container40966 item.
            /// </summary>
            [RepositoryItem("07e08ad3-675e-45c4-8f2e-7f451b98f81f")]
            public virtual Ranorex.Container Container40966
            {
                get
                {
                    return _container40966Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Container40966 item info.
            /// </summary>
            [RepositoryItemInfo("07e08ad3-675e-45c4-8f2e-7f451b98f81f")]
            public virtual RepoItemInfo Container40966Info
            {
                get
                {
                    return _container40966Info;
                }
            }

            /// <summary>
            /// The ControlBandClass item.
            /// </summary>
            [RepositoryItem("9ccca334-a1bc-411d-965a-e0378d6c5459")]
            public virtual Ranorex.Unknown ControlBandClass
            {
                get
                {
                    return _controlbandclassInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ControlBandClass item info.
            /// </summary>
            [RepositoryItemInfo("9ccca334-a1bc-411d-965a-e0378d6c5459")]
            public virtual RepoItemInfo ControlBandClassInfo
            {
                get
                {
                    return _controlbandclassInfo;
                }
            }

            /// <summary>
            /// The CloseTabCtrlPlusW item.
            /// </summary>
            [RepositoryItem("340b592d-8784-413c-80ea-0854725ee605")]
            public virtual Ranorex.Button CloseTabCtrlPlusW
            {
                get
                {
                    return _closetabctrlpluswInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseTabCtrlPlusW item info.
            /// </summary>
            [RepositoryItemInfo("340b592d-8784-413c-80ea-0854725ee605")]
            public virtual RepoItemInfo CloseTabCtrlPlusWInfo
            {
                get
                {
                    return _closetabctrlpluswInfo;
                }
            }
        }

        /// <summary>
        /// The WelcomeProMonitorAppFolder folder.
        /// </summary>
        [RepositoryFolder("a97540b1-e8aa-4085-b035-3aac8f33827f")]
        public partial class WelcomeProMonitorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _contentfullheightInfo;
            RepoItemInfo _accountlandingemailInfo;
            RepoItemInfo _httpsisstgweb2promonitorcaimageslInfo;

            /// <summary>
            /// Creates a new WelcomeProMonitor  folder.
            /// </summary>
            public WelcomeProMonitorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeProMonitor", "/dom[@domain='isstgweb2.promonitor.ca']", parentFolder, 30000, null, false, "a97540b1-e8aa-4085-b035-3aac8f33827f", "")
            {
                _contentfullheightInfo = new RepoItemInfo(this, "ContentFullHeight", ".//body[#'Account_Landing']/div[2]/div", 30000, null, "c54cf65a-6272-4b0d-92a4-2379d60a429d");
                _accountlandingemailInfo = new RepoItemInfo(this, "AccountLandingEmail", ".//input[#'Account_Landing_Email']", 30000, null, "f39dfd58-6e6e-4d1b-bcf0-a643d8571bdf");
                _httpsisstgweb2promonitorcaimageslInfo = new RepoItemInfo(this, "HttpsIsstgweb2PromonitorCaImagesL", ".//body[#'Account_Landing']/div[1]/?/?/table//img[@src='https://isstgweb2.promonitor.ca/Images/Landing/ProMonitor_Logo_dark-outline.png']", 30000, null, "e6d289f8-7ff1-4e1d-ac76-9aecfb4ea82b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a97540b1-e8aa-4085-b035-3aac8f33827f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a97540b1-e8aa-4085-b035-3aac8f33827f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContentFullHeight item.
            /// </summary>
            [RepositoryItem("c54cf65a-6272-4b0d-92a4-2379d60a429d")]
            public virtual Ranorex.DivTag ContentFullHeight
            {
                get
                {
                    return _contentfullheightInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ContentFullHeight item info.
            /// </summary>
            [RepositoryItemInfo("c54cf65a-6272-4b0d-92a4-2379d60a429d")]
            public virtual RepoItemInfo ContentFullHeightInfo
            {
                get
                {
                    return _contentfullheightInfo;
                }
            }

            /// <summary>
            /// The AccountLandingEmail item.
            /// </summary>
            [RepositoryItem("f39dfd58-6e6e-4d1b-bcf0-a643d8571bdf")]
            public virtual Ranorex.InputTag AccountLandingEmail
            {
                get
                {
                    return _accountlandingemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountLandingEmail item info.
            /// </summary>
            [RepositoryItemInfo("f39dfd58-6e6e-4d1b-bcf0-a643d8571bdf")]
            public virtual RepoItemInfo AccountLandingEmailInfo
            {
                get
                {
                    return _accountlandingemailInfo;
                }
            }

            /// <summary>
            /// The HttpsIsstgweb2PromonitorCaImagesL item.
            /// </summary>
            [RepositoryItem("e6d289f8-7ff1-4e1d-ac76-9aecfb4ea82b")]
            public virtual Ranorex.ImgTag HttpsIsstgweb2PromonitorCaImagesL
            {
                get
                {
                    return _httpsisstgweb2promonitorcaimageslInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsIsstgweb2PromonitorCaImagesL item info.
            /// </summary>
            [RepositoryItemInfo("e6d289f8-7ff1-4e1d-ac76-9aecfb4ea82b")]
            public virtual RepoItemInfo HttpsIsstgweb2PromonitorCaImagesLInfo
            {
                get
                {
                    return _httpsisstgweb2promonitorcaimageslInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}